default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_cep_development

test:
  <<: *default
  database: search_cep_test

production:
  <<: *default
  database: search_cep_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
